services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000/api}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID:-}
    image: itzdineshyadav/data-analyzer:client
    container_name: data-analyzer-client
    restart: unless-stopped
    ports:
      - "3000:3000"
